name: Rust Build
on: [push, pull_request]
env:
  ORT_STRATEGY: system
  ORT_LIB_LOCATION: ./onnxruntime-linux-x64-1.14.1/lib/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: default
    - name: Install requirement
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
    - name: Download Onnx runtime
      run: wget https://github.com/microsoft/onnxruntime/releases/download/v1.14.1/onnxruntime-linux-x64-1.14.1.tgz && tar -xzvf onnxruntime-linux-x64-1.14.1.tgz
    - name: Build
      run: cargo build --bin clip-as-service-server --release
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: clip-as-service-server
        path: target/release/clip-as-service-server
