name: Rust Build
on: [push, pull_request]
env:
  ORT_STRATEGY: download
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: default
    - name: Install requirement
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
    - name: Build
      run: cargo build --bin clip-as-service-server --release
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: clip-as-service-server
        path: target/release/clip-as-service-server
